baseURL: https://thankful-smoke-02ad82403.2.azurestaticapps.net # todo: change site url.
title: Photographie # todo: change site name.
defaultContentLanguage: 'fr'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  subtitle: Mes photographies. # todo: change default subtitle for your website.
  copyright: All rights reserved. # todo: set your copyright type.
  author: Sébastien VASSEUR # todo: set your full name.
  dontShowSource: false # please, do not do this :)
  portfolio:
    columns:
      desktop:
        paris: 3
        facade: 4
        archive: 6
        expo: 3
        default: 3
      mobile:
        default: 2
        archive: 3
  socials:
    # todo: change these links.
    - icon: 'fa fa-camera-retro fa-lg'
      url: 'https://sebastienvasseur.myportfolio.com/'
      landing: true
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:sebastien.vasseur@gmail.com'
      landing: true
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://instagram.com/svasseur'
      landing: true
  homepage: "/work" # homepage link, mostly same with menu.main[0]
  specialPages:
    - work
    - archive
  bypassWelcomePage: true # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: false # disables the background image on the homepage
  plausible: '' # todo: set your plausible id.
  disableRadius: false
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: work
      url: /work/
      weight: 1
    - name: Paris
      url: /tags/paris/
      weight: 2
    - name: façades
      url: /tags/facade/
      weight: 3
    - name: archive
      url: /tags/archive/
      weight: 4
    - name: expo
      url: /tags/expo/
      weight: 5
    - name: test
      url: /test/
      weight: 6
    - name: about
      url: /about/
      weight: 7
